//
//  SearchModels.swift
//  AiportFinder
//
//  Created by Eduardo Batista on 04/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Airport {
    let name: String
    let code: String
    let latitude: Double
    let longitude: Double
}

enum Search {
    // MARK: Use cases
    enum Data {
        struct Request: Codable {
            let lat: String
            let lon: String
            let radius: String
        }
        struct Response: Codable {
            var name: String?
            var alpha2countryCode: String?
            var latitude: Double?
            var longitude: Double?
        }
        struct ViewModel {
            let ariports: [Airport]
        }
    }
}
