//
//  SearchRouter.swift
//  AiportFinder
//
//  Created by Eduardo Batista on 04/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToTabBarController()
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    
    
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    // MARK: Routing
    
    func routeToTabBarController() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let tabBarController = storyboard.instantiateViewController(withIdentifier: "TabBarControllerIdentifier") as? UITabBarController else {
            return
        }
        if let destinationMapVC = tabBarController.viewControllers?.first as? MapViewController {
            var destinationMapDS = destinationMapVC.router!.dataStore!
            passDataToMap(source: dataStore!, destination: &destinationMapDS)
        }
        
        if let destinationListVC = tabBarController.viewControllers?[1] as? ListViewController {
            var destinationListDS = destinationListVC.router!.dataStore!
            passDataToList(sourse: dataStore!, destination: &destinationListDS)
        }
        
        viewController?.navigationController?.pushViewController(tabBarController, animated: true)
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: SearchViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    func passDataToMap(source: SearchDataStore, destination: inout MapDataStore) {
        destination.airports = source.airports
        destination.currentLatitude = source.currentLatitude
        destination.currentLongitude = source.currentLongitude
        destination.radiusSelected = source.radiusSelected
    }
    
    func passDataToList(sourse: SearchDataStore, destination: inout ListDataStore) {
        destination.airports = sourse.airports
    }
}
