//
//  SearchInteractor.swift
//  AiportFinder
//
//  Created by Eduardo Batista on 04/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    func doSearchAirports(request: Search.Data.Request)
}

protocol SearchDataStore {
    //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {

    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    //var name: String = ""
    
    // MARK: Do Search Airports
    
    func doSearchAirports(request: Search.Data.Request) {
        worker = SearchWorker()
        worker?.doSearchAirportsWork(with: request,completionHandler: { result in
            switch result {
            case .success(let response):
                self.presenter?.presentAirport(response: response)
            case .failure(let error):
                self.presenter?.presentError(error: error)
            }
        })
    }
    
}
