//
//  SearchPresenter.swift
//  AiportFinder
//
//  Created by Eduardo Batista on 04/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentAirport(response: [Search.Data.Response])
    func presentError(error: Error)
}

class SearchPresenter: SearchPresentationLogic {
  
    weak var viewController: SearchDisplayLogic?
    
    func presentAirport(response: [Search.Data.Response]) {
        var airports: [Airport] = []
        for airport in response {
            let newAirport = Airport(name: airport.name ?? "No name", code: airport.alpha2countryCode ?? "No code", latitude: airport.latitude ?? 0.0, longitude: airport.longitude ?? 0.0)
            airports.append(newAirport)
        }
        let viewModel = Search.Data.ViewModel(ariports: airports)
        viewController?.displayAirports(viewModel: viewModel)
    }
    
    func presentError(error: any Error) {
        viewController?.displayError(error: error)
    }
}
