//
//  RadiusInteractor.swift
//  AiportFinder
//
//  Created by Eduardo Batista on 04/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RadiusBusinessLogic {
    func doSomething(request: Radius.Something.Request)
}

protocol RadiusDataStore {
    //var name: String { get set }
}

class RadiusInteractor: RadiusBusinessLogic, RadiusDataStore {
    var presenter: RadiusPresentationLogic?
    var worker: RadiusWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Radius.Something.Request) {
        
        worker = RadiusWorker()
        worker?.doSomeWork()
        
        let response = Radius.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
